jest.mock("next/navigation", () => ({ useRouter: () => ({ push: jest.fn() }) }));
jest.mock("@/lib/market-data/service", () => ({ ...jest.requireActual("@/lib/market-data/service"), loadHistory: jest.fn() }));
jest.mock("@/components/markets/ThemeHistoryChart", () => ({ ThemeHistoryChart: () => <div data-testid="industry-chart" /> }));
import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { ThemeDetail } from "@/components/markets/ThemeDetail";
import { marketThemes } from "@/data/market-themes";
import { fundamentalsSource } from "@/lib/fundamentals/snapshot-source";
import { loadHistory } from "@/lib/market-data/service";
import { getBrowserMarketDataCache } from "@/lib/market-data/cache/market-cache";

test("the persisted universe powers all views; partial history is never presented as whole-industry performance", async () => {
  await getBrowserMarketDataCache().clearMarketData();
  const industry = fundamentalsSource.getIndustries().ai;
  const included = industry.members.slice(0, 2).map((row) => row.asset.id);
  jest.mocked(loadHistory).mockImplementation(async (asset, range) => {
    if (!included.includes(asset.id)) throw new Error("No history in test fixture");
    const start = Date.parse(range.from);
    const length = Math.round((Date.parse(range.to) - start) / 86400000) + 1;
    return { asset, range, source: "network", points: Array.from({ length }, (_, i) => ({ assetId: asset.id, date: new Date(start + i * 86400000).toISOString().slice(0, 10), close: 100 + i, currency: asset.currency, adjustedForSplits: true })) };
  });
  const bounds = jest.spyOn(HTMLElement.prototype, "getBoundingClientRect").mockReturnValue({ width: 800, height: 360, top: 0, left: 0, bottom: 360, right: 800, x: 0, y: 0, toJSON: () => ({}) });
  render(<ThemeDetail theme={marketThemes[0]} locale="cs-CZ" industry={industry} />);
  await screen.findByText("Nedostatečné pokrytí historických dat");
  expect(screen.queryByTestId("industry-chart")).not.toBeInTheDocument();
  expect(loadHistory).toHaveBeenCalledTimes(industry.members.length);
  expect(screen.getByText(new RegExp(`Historie je dostupná pro 2 z ${industry.members.length}`))).toBeVisible();
  expect(screen.getByText("Celková kapitalizace")).toBeVisible();
  expect(screen.getByText("Souhrnné roční tržby")).toBeVisible();
  const map = screen.getByRole("region", { name: "Mapa odvětví" });
  expect(within(map).getAllByRole("link")).toHaveLength(industry.members.length);
  await userEvent.click(screen.getByText(/Prozkoumat všechny firmy/));
  bounds.mockRestore();
  const table = screen.getByRole("region", { name: "Firmy v odvětví" });
  expect(within(table).getAllByRole("row")).toHaveLength(industry.members.length + 1);
  await userEvent.click(screen.getByRole("button", { name: "1Y" }));
  expect(screen.queryByRole("group", { name: "Vážení indexu" })).not.toBeInTheDocument();
  expect(screen.queryByText("Výnos za 1Y")).not.toBeInTheDocument();
  expect(screen.queryByRole("progressbar")).not.toBeInTheDocument();
  expect(loadHistory).toHaveBeenCalledTimes(industry.members.length);
  expect(screen.getByText(new RegExp(`Historie je dostupná pro 2 z ${industry.members.length}`))).toBeVisible();
});
